CREATE TABLE USUARIO (
  idUsuario INT NOT NULL AUTO_INCREMENT,
  Login VARCHAR(255) NOT NULL,
  Senha VARCHAR(255) NULL,
  NomeCompleto VARCHAR(100) NULL,
  Email VARCHAR(100) NULL,
  Descricao VARCHAR(100) NULL,
  Ativo TINYINT(1) NULL,
  PRIMARY KEY (idUsuario),
  UNIQUE INDEX Login_UNIQUE (Login ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USUARIO (idUsuario, Login, Senha, NomeCompleto, Email, Descricao, Ativo) VALUES (1, 'admin', '$2a$10$/qBSCFmqbqSX010h3E8no..lGKyvc0dDg614Fgw1J.68BeamxWyFy', 'Usuário Admin', 'admin@admin.com', 'Usuário Admin', 1);

CREATE TABLE GRUPO (
  idGrupo INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(100) NULL,
  PRIMARY KEY (idGrupo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USUARIO_GRUPO (
  idGrupo INT NOT NULL,
  idUsuario INT NOT NULL,
  INDEX fk_USUARIO_GRUPO_GRUPO1_idx (idGrupo ASC),
  INDEX fk_USUARIO_GRUPO_USUARIO1_idx (idUsuario ASC),
  PRIMARY KEY (idGrupo),
  CONSTRAINT fk_USUARIO_GRUPO_GRUPO1
    FOREIGN KEY (idGrupo)
    REFERENCES GRUPO (idGrupo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_USUARIO_GRUPO_USUARIO1
    FOREIGN KEY (idUsuario)
    REFERENCES USUARIO (idUsuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ENTIDADE (
  idEntidade INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(45) NULL,
  NomeTabelaBanco VARCHAR(45) NULL,
  Descricao VARCHAR(100) NULL,
  PRIMARY KEY (idEntidade),
  UNIQUE INDEX Nome_UNIQUE (Nome ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE PERMISSAO (
  idGrupo INT NOT NULL,
  idEntidade INT NOT NULL,
  canInsert TINYINT(1) NULL,
  canUpdate TINYINT(1) NULL,
  canDelete TINYINT(1) NULL,
  canView TINYINT(1) NULL,
  INDEX fk_PERMISSAO_GRUPO1_idx (idGrupo ASC),
  INDEX fk_PERMISSAO_ENTIDADE1_idx (idEntidade ASC),
  PRIMARY KEY (idGrupo, idEntidade),
  CONSTRAINT fk_PERMISSAO_GRUPO1
    FOREIGN KEY (idGrupo)
    REFERENCES GRUPO (idGrupo)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_PERMISSAO_ENTIDADE1
    FOREIGN KEY (idEntidade)
    REFERENCES ENTIDADE (idEntidade)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;