CREATE TABLE LAREIRA (
  idLareira INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(45) NULL,
  Endereco VARCHAR(100) NULL,
  Bairro VARCHAR(45) NULL,
  CEP VARCHAR(45) NULL,
  Cidade VARCHAR(45) NULL,
  Estado CHAR(2) NULL,
  Telefone VARCHAR(45) NULL,
  PRIMARY KEY (idLareira)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO LAREIRA VALUES (1,'Lareira Cascavel','Rua Santa Catarina','Centro','85806250','Cascavel','PR','(45) 9 9999-4545');
INSERT INTO LAREIRA VALUES (2,'Lareira São Cristóvão, Cascavel','Rua das amélias','São Cristóvão','85806250','Cascavel','PR','(45) 9 9929-4879');

CREATE TABLE CASAL (
  idCasal INT NOT NULL AUTO_INCREMENT,
  idLareira INT NOT NULL,
  MaridoNome VARCHAR(45) NULL,
  MaridoSobrenome VARCHAR(45) NULL,
  MaridoDataNascimento DATE NULL,
  MaridoProfissao VARCHAR(45) NULL,
  MaridoTelCelular VARCHAR(45) NULL,
  MaridoEmail VARCHAR(70) NULL,
  MaridoProblemaSaude VARCHAR(80) NULL,
  EsposaNome VARCHAR(45) NULL,
  EsposaSobrenome VARCHAR(45) NULL,
  EsposaDataNascimento DATE NULL,
  EsposaProfissao VARCHAR(45) NULL,
  EsposaTelCelular VARCHAR(45) NULL,
  EsposaEmail VARCHAR(70) NULL,
  EsposaProblemaSaude VARCHAR(80) NULL,
  PRIMARY KEY (idCasal),
  INDEX fk_CASAL_LAREIRA1_idx (idLareira ASC),
  CONSTRAINT fk_CASAL_LAREIRA1
    FOREIGN KEY (idLareira)
    REFERENCES LAREIRA (idLareira)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FILHO (
  IdFilho INT NOT NULL AUTO_INCREMENT,
  idCasal INT NOT NULL,
  Nome VARCHAR(45) NULL,
  Sexo CHAR(2) NULL,
  DataNascimento DATE NULL,
  PRIMARY KEY (IdFilho),
  INDEX fk_FILHO_CASAL1_idx (idCasal ASC),
  CONSTRAINT fk_FILHO_CASAL1
    FOREIGN KEY (idCasal)
    REFERENCES CASAL (idCasal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE FUNCAO (
  idFuncao INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(50) NULL,
  PRIMARY KEY (idFuncao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE SETOR (
  idSetor INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(50) NULL,
  PRIMARY KEY (idSetor)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;