CREATE TABLE GRUPO_PERSEVERANCA (
  idGP INT NOT NULL AUTO_INCREMENT,
  idLareira INT NOT NULL,
  Nome VARCHAR(45) NULL,
  DataInicio DATE NULL,
  PRIMARY KEY (idGP),
  INDEX fk_GRUPO_PERSEVERANCA_LAREIRA1_idx (idLareira ASC),
  CONSTRAINT fk_GRUPO_PERSEVERANCA_LAREIRA1
    FOREIGN KEY (idLareira)
    REFERENCES LAREIRA (idLareira)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GRUPO_PERSEVERANCA_FUNCAO (
  idGPFuncao INT NOT NULL AUTO_INCREMENT,
  Nome VARCHAR(50) NULL,
  PRIMARY KEY (idGPFuncao)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE GRUPO_PERSEVERANCA_CASAIS (
  idGpCasal INT NOT NULL,
  idGP INT NOT NULL,
  idCasal INT NOT NULL,
  idGPFuncao INT NOT NULL,
  PRIMARY KEY (idGpCasal),
  INDEX fk_GRUPO_PERSEVERANCA_CASAIS_CASAL1_idx (idCasal ASC),
  INDEX fk_GRUPO_PERSEVERANCA_CASAIS_GRUPO_PERSEVERANCA_FUNCAO1_idx (idGPFuncao ASC),
  CONSTRAINT fk_GRUPO_PERSEVERANCA_CASAIS_GRUPO_PERSEVERANCA1
    FOREIGN KEY (idGP)
    REFERENCES GRUPO_PERSEVERANCA (idGP)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GRUPO_PERSEVERANCA_CASAIS_CASAL1
    FOREIGN KEY (idCasal)
    REFERENCES CASAL (idCasal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_GRUPO_PERSEVERANCA_CASAIS_GRUPO_PERSEVERANCA_FUNCAO1
    FOREIGN KEY (idGPFuncao)
    REFERENCES GRUPO_PERSEVERANCA_FUNCAO (idGPFuncao)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE LIVRO_PRESENCA_PERSEVERANCA (
  idPresenca INT NOT NULL,
  idGP INT NOT NULL AUTO_INCREMENT,
  idCasalAnfitriao INT NOT NULL,
  Data DATE NOT NULL,
  HORA TIME NOT NULL,
  PRIMARY KEY (idPresenca),
  INDEX fk_LIVRO_PRESENCA_PERSEVERANCA_CASAL1_idx (idCasalAnfitriao ASC),
  CONSTRAINT fk_LIVRO_PRESENCA_PERSEVERANCA_GRUPO_PERSEVERANCA1
    FOREIGN KEY (idGP)
    REFERENCES GRUPO_PERSEVERANCA (idGP)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_LIVRO_PRESENCA_PERSEVERANCA_CASAL1
    FOREIGN KEY (idCasalAnfitriao)
    REFERENCES CASAL (idCasal)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;